export interface DayData {
  day: number;
  mission: string;
  environments: string[];
  assumption: string;
  safetyBehavior: string;
  internalFocus: string;
  script: string;
  defaultLearning: string;
}

export const DAYS: DayData[] = [
  {
    day: 1,
    mission: "Sair por pelo menos 15 minutos, apenas observando pessoas (sem interagir)",
    environments: ["Rua", "Praça", "Shopping", "Praia", "Parque"],
    assumption: "Se eu olhar para as pessoas, vou perceber que estão me encarando de forma negativa.",
    safetyBehavior: "Olhar para o chão",
    internalFocus: "Pensar no que devo fazer e em como estou me sentindo",
    script: "Olhar para as pessoas em alguns momentos e contar quantas realmente estão me encarando (não apenas olhando), focando nelas e não em mim.",
    defaultLearning: "Não estou no centro da atenção das outras pessoas – elas até olham, mas isso é diferente de encarar.",
  },
  {
    day: 2,
    mission: "Sentar em um lugar público e ficar 10 minutos apenas ouvindo outras pessoas que estejam conversando",
    environments: ["Praça", "Shopping", "Praia", "Parque", "Café"],
    assumption: "Se me concentrar no que as outras pessoas falam, vou perceber que sempre são coisas interessantes.",
    safetyBehavior: "Olhar o celular com frequência",
    internalFocus: "Me comparar com elas e focar em como estou me sentindo",
    script: "Me concentrar no que as pessoas estão falando, sem me comparar e sem olhar no celular.",
    defaultLearning: "A maioria das conversas não são fascinantes. As pessoas apenas jogam conversa fora, coisas banais.",
  },
  {
    day: 3,
    mission: "Fazer contato visual com pelo menos 3 pessoas diferentes",
    environments: ["Rua", "Praça", "Shopping", "Praia", "Parque", "Corredor", "Elevador"],
    assumption: "Se eu olhar nos olhos das pessoas, elas vão ficar incomodadas e reagir mal.",
    safetyBehavior: "Desviar o olhar ou olhar para o chão.",
    internalFocus: "Imaginar o que estão pensando de mim ou focar em como estou me sentindo.",
    script: "Manter contato visual por 3 segundos e focar apenas na pessoa, não em como me sinto.",
    defaultLearning: "As pessoas são menos hostis e menos reativas do que eu imagino.",
  },
  {
    day: 4,
    mission: "Colocar uma foto sua no perfil e postar uma foto (story ou feed)",
    environments: ["Instagram", "WhatsApp", "Facebook"],
    assumption: "As pessoas vão reagir negativamente (comentários negativos, mensagens críticas).",
    safetyBehavior: "Apagar ou remover a foto.",
    internalFocus: "Imaginar avaliações das pessoas e ficar esperando por reações.",
    script: "Postar a foto e não esperar por reações ou comentários, focar em qualquer outra coisa durante esse dia.",
    defaultLearning: "Não estou no centro das atenções das outras pessoas. O que faço não gera tanto burburinho quanto pensei.",
  },
  {
    day: 5,
    mission: "Enviar um meme, post ou vídeo para alguém que não conversa há um tempo",
    environments: ["WhatsApp", "Instagram", "TikTok"],
    assumption: "Se eu apenas enviar sem pensar muito, vou ser inconveniente e a pessoa irá reclamar.",
    safetyBehavior: "Adicionar explicações ou gastar tempo procurando o post perfeito.",
    internalFocus: "Imaginar o que a pessoa está pensando sobre mim e focar em como estou me sentindo.",
    script: "Enviar o conteúdo citando algo sobre ela, ou apenas enviar sem explicação, e observar o que acontece.",
    defaultLearning: "As pessoas não reagem de forma negativa o tempo todo, eu posso arriscar um pouco.",
  },
  {
    day: 6,
    mission: "Cumprimentar 2 pessoas",
    environments: ["Prédio", "Rua", "Comércio", "Vizinho", "Atendente", "Porteiro"],
    assumption: "Se eu apenas cumprimentar sem planejar, vou falar de forma estranha e vão rir de mim.",
    safetyBehavior: "Planejar como irei cumprimentar.",
    internalFocus: "Imaginar como a pessoa vai reagir e focar em como estou me sentindo.",
    script: "Cumprimentar sem planejar o que irei dizer focando na resposta da pessoa, não em mim.",
    defaultLearning: "Eu não erro tanto quanto pensei; quando planejo, parece que erro mais ainda.",
  },
  {
    day: 7,
    mission: "Fazer uma pergunta objetiva para um atendente",
    environments: ["Supermercado", "Farmácia", "Loja"],
    assumption: "Se eu perguntar sem planejar demais, não vou conseguir falar e vou ser ignorado.",
    safetyBehavior: "Planejar como irei fazer a pergunta.",
    internalFocus: "Focar em como estou falando e em como estou me sentindo.",
    script: "Fazer a pergunta sem planejar demais e observar atentamente a resposta do atendente.",
    defaultLearning: "Quando falo sem planejar, eu erro menos. E mesmo quando erro, percebo que a pessoa não reage tão negativamente quanto pensei.",
  },
  {
    day: 8,
    mission: "Cumprimentar um grupo de 2–4 pessoas",
    environments: ["Elevador", "Corredor", "Entrada do trabalho"],
    assumption: "Se eu apenas cumprimentar sem planejar, vou falar de forma estranha e vão rir de mim.",
    safetyBehavior: "Planejar como irei cumprimentar.",
    internalFocus: "Imaginar como a pessoa vai reagir e focar em como estou me sentindo.",
    script: "Cumprimentar sem planejar o que irei dizer focando na resposta da pessoa, não em mim.",
    defaultLearning: "Eu não erro tanto quanto pensei; quando planejo, parece que erro mais ainda.",
  },
  {
    day: 9,
    mission: "Ligar para um serviço e pedir informações",
    environments: ["Telefone"],
    assumption: "Se eu apenas ligar sem antes fazer um roteiro, não vou saber o que dizer e a pessoa vai perder a paciência.",
    safetyBehavior: "Fazer um roteiro do que dizer.",
    internalFocus: "Planejar o que irei dizer enquanto a pessoa está falando.",
    script: "Fazer a ligação 1 minuto depois de ler esse card, sem fazer nenhum roteiro do que dizer, apenas dizendo o que vier à mente.",
    defaultLearning: "Eu não erro tanto quanto pensei quando não faço roteiros. Dá para arriscar ser mais espontâneo.",
  },
  {
    day: 10,
    mission: "Perguntar sobre características de um produto",
    environments: ["Loja", "Mercado"],
    assumption: "Se eu perguntar sem planejar demais, vou falar de forma estranha e não vou conseguir manter a conversa.",
    safetyBehavior: "Planejar como irei fazer a pergunta.",
    internalFocus: "Focar em como estou falando e em como estou me sentindo.",
    script: "Fazer a pergunta sem planejar demais e ouvir com muita atenção a resposta do atendente, para saber se terei mais dúvidas.",
    defaultLearning: "A sensação de não ter o que falar vem quando me monitoro e foco em mim, ao invés de ouvir o que a pessoa fala.",
  },
  {
    day: 11,
    mission: "Enviar mensagem para alguém que talvez queira conhecer",
    environments: ["Instagram", "Tinder", "Apps de relacionamento"],
    assumption: "Se eu não encontrar algo perfeito para dizer, a pessoa vai me constranger ou me ignorar.",
    safetyBehavior: "Procurar a mensagem perfeita ou não enviar nada.",
    internalFocus: "Imaginar o que a pessoa vai pensar de mim.",
    script: "Apenas enviar a mensagem sem planejar demais, e não ficar esperando uma resposta. Fechar o app e só abrir se chegar a notificação.",
    defaultLearning: "As pessoas não esperam que eu seja interessante o tempo todo. E levar um vácuo não acaba com minha vida, posso tentar de novo.",
  },
  {
    day: 12,
    mission: "Perguntar sobre características de um produto, mas perguntar algo óbvio, ou errar uma palavra de propósito",
    environments: ["Loja", "Mercado"],
    assumption: "Se eu errar ou falar algo óbvio, a pessoa vai ser hostil ou me humilhar.",
    safetyBehavior: "Se esforçar para fazer tudo corretamente.",
    internalFocus: "Imaginar o que a pessoa está pensando de mim e focar em como estou me sentindo.",
    script: "Errar propositalmente ou perguntar algo óbvio, e focar no que a pessoa responde e na reação dela, não no que sinto.",
    defaultLearning: "Todo mundo comete erros, as pessoas não esperam que eu saiba tudo.",
  },
  {
    day: 13,
    mission: "Fazer uma pergunta espontânea para atendente",
    environments: ["Caixa", "Padaria"],
    assumption: "Se eu perguntar algo espontâneo, como 'tá tendo muito movimento hoje?' / 'Você deve estar doida para ir embora, fecha que horas?', a pessoa vai me achar estranho e me ignorar.",
    safetyBehavior: "Planejar como irei dizer.",
    internalFocus: "Imaginar o que a pessoa está pensando de mim e focar em como estou me sentindo.",
    script: "Fazer a pergunta da forma que vier na minha mente, sem pensar demais, focar no que a pessoa responde.",
    defaultLearning: "Sentir que estou agindo estranho é resultado de monitorar o quão estranho estou agindo. Se meu foco está na pessoa, eu nem penso nisso.",
  },
  {
    day: 14,
    mission: "Perguntar como alguém está (como você está, como foi seu dia) e ouvir de verdade",
    environments: ["Trabalho", "Família"],
    assumption: "Se eu apenas me concentrar no que a pessoa fala, não vou saber o que responder quando ela terminar.",
    safetyBehavior: "Planejar o que responder enquanto a pessoa está falando.",
    internalFocus: "Focar nos meus pensamentos e no que estou sentindo.",
    script: "Fazer a pergunta e ouvir detalhe por detalhe do que ela responde. Se me distrair em algum momento, pedir para repetir a parte que perdi.",
    defaultLearning: "Não ter assunto é resultado de ficar monitorando se estou agindo certo e buscando a coisa certa a dizer. Quando ouço os detalhes, o assunto vem.",
  },
  {
    day: 15,
    mission: "Fazer um elogio genuíno para um desconhecido",
    environments: ["Rua", "Loja", "Atendente", "Colega de trabalho", "Família"],
    assumption: "Se eu elogiar a pessoa, ou um acessório, ou a roupa, vou ser invasivo, ela vai me ignorar ou ser hostil.",
    safetyBehavior: "Planejar demais o elogio perfeito.",
    internalFocus: "Imaginar o que a pessoa vai pensar e focar no que estou sentindo.",
    script: "Fazer o elogio sem pensar demais e focar na reação da pessoa, não no que eu sinto.",
    defaultLearning: "As pessoas são receptivas quando falo o que penso, não preciso planejar tanto.",
  },
  {
    day: 16,
    mission: "Pedir opinião a outro cliente",
    environments: ["Loja", "Mercado"],
    assumption: "Se eu peço opinião como 'estou em dúvida em uma roupa para minha irmã, você acha essa bonita?', vão me achar estranho e ignorar.",
    safetyBehavior: "Planejar muito antes de dizer ou evitar falar.",
    internalFocus: "Imaginar o que a pessoa vai pensar e focar no que estou sentindo.",
    script: "Pedir a opinião sem pensar demais e ouvir atentamente a resposta. Se me distrair, pedir para que repita a parte que perdi.",
    defaultLearning: "Nem tudo incomoda as pessoas, eu posso arriscar puxar assunto de vez em quando.",
  },
  {
    day: 17,
    mission: "Comentar algo sobre o ambiente",
    environments: ["Fila", "Transporte", "Sala de espera", "Parque", "Praça", "Shopping", "Evento"],
    assumption: "Se eu comentar sobre algo, e não planejar a conversa completa, não vou saber o que responder em seguida.",
    safetyBehavior: "Planejar o diálogo completo antes dele acontecer.",
    internalFocus: "Imaginar o que dizer em seguida e focar no que estou sentindo.",
    script: "Dizer a primeira coisa que vier na minha cabeça e focar na resposta da pessoa e no ambiente, não em mim.",
    defaultLearning: "A maioria das conversas não são fascinantes. Não preciso sempre ter algo incrível para que a pessoa queira responder.",
  },
  {
    day: 18,
    mission: "Fazer uma pergunta aberta para alguém conhecido",
    environments: ["Trabalho", "Faculdade"],
    assumption: "Se eu perguntar coisas como 'O que fez escolher esse curso/profissão?' ou 'Como você aprendeu a fazer isso?', sem planejar o diálogo completo, não vou saber o que dizer em seguida.",
    safetyBehavior: "Planejar o diálogo completo antes dele acontecer ou mudar de assunto rápido.",
    internalFocus: "Imaginar o que dizer em seguida e focar no que estou sentindo.",
    script: "Fazer a pergunta e ouvir com detalhes a resposta da pessoa, e ir respondendo o que vier à mente, focando no que ela fala, não em mim.",
    defaultLearning: "Não preciso roteirizar o diálogo completo. Quando ouço os detalhes, a conversa flui.",
  },
  {
    day: 19,
    mission: "Ter uma conversa de pelo menos 2 minutos com foco total no que a pessoa diz",
    environments: ["Qualquer ambiente social"],
    assumption: "Se eu não planejar com antecedência o diálogo, vou falar besteira ou ficar sem assunto e a conversa vai morrer antes dos 2 minutos.",
    safetyBehavior: "Planejar o diálogo completo.",
    internalFocus: "Imaginar o que dizer em seguida e focar no que estou sentindo.",
    script: "Focar totalmente nos detalhes do que a pessoa diz, e ir respondendo o que vier à mente, focando no que ela fala, não em mim.",
    defaultLearning: "Me sentir entediante, sem assunto, é resultado de me monitorar, focar em mim e ficar buscando a coisa perfeita a dizer.",
  },
  {
    day: 20,
    mission: "Compartilhar uma opinião pessoal pequena",
    environments: ["Conversas cotidianas"],
    assumption: "Se eu der uma opinião, mesmo que simples, vou ser inadequado e vão me excluir da conversa ou brigar.",
    safetyBehavior: "Censurar o que quero dizer.",
    internalFocus: "Imaginar como a pessoa vai reagir e focar no que sinto.",
    script: "Expressar a opinião da forma que vier na minha cabeça e me expressar genuinamente (sem ofender nem ser hostil).",
    defaultLearning: "As pessoas me aceitam quando sou eu mesmo, não preciso me censurar: posso ser espontâneo.",
  },
  {
    day: 21,
    mission: "Manter uma conversa espontânea de pelo menos 5 minutos com alguém novo",
    environments: ["Eventos", "Fila", "Ambiente social", "Encontro", "Bar", "Festa"],
    assumption: "Se eu apenas falar o vier à minha mente, sem planejar ou procurar coisas interessantes, vou ser ignorado ou vamos ficar sem assunto, calados.",
    safetyBehavior: "Planejar e procurar a coisa perfeita a dizer.",
    internalFocus: "Avaliar meu desempenho e focar no que sinto.",
    script: "Falar naturalmente o que vier à minha mente, sem censurar, mesmo que pareça irrelevante, e ouvir atentamente cada detalhe do que a pessoa diz, focando nela, não no que sinto nem no meu desempenho.",
    defaultLearning: "As pessoas me aceitam quando sou eu mesmo, não preciso me censurar nem dizer coisas incríveis ou engraçadas o tempo todo: posso ser espontâneo.",
  },
];

export function getDayData(dayNumber: number): DayData | undefined {
  return DAYS.find((d) => d.day === dayNumber);
}
